	            <div class="clear"></div>
    	        <?php include dirname(__FILE__).'/rssfeed.php'; ?>
		    </div>

    	    <div id="footer">
    	        <div class="version pull-left">
    	            <a target="_blank" href="https://phplist.com">&copy; phpList ltd.</a> - v<?php echo VERSION?>               
    	        </div>
    	        <div class="ressources pull-right">
    	            <a target="_blank" href="https://resources.phplist.com">Resources</a>&nbsp; |  
    	            <a target="_blank" href="http://twitter.com/phplist">twitter</a>
    	        </div>
    	    </div>
    	</div> <!-- end #content -->
	</div> <!-- end #container -->
</div> <!-- end .container-fluid-->

<script type="text/javascript" src="ui/phplist-ui-bootstrap/js/jquery-1.12.1.min.js"></script>
<script type="text/javascript" src="js/phplistapp.js"></script>
<script type="text/javascript" src="ui/phplist-ui-bootstrap/js/phpList3ToBootstrap.js"></script>
<script type="text/javascript" src="ui/phplist-ui-bootstrap/bootstrap/dist/js/bootstrap.min.js"></script>
<script type="text/javascript" src="ui/phplist-ui-bootstrap/js/jcarousellite_1.0.1.min.js"></script>
<script type="text/javascript" src="ui/phplist-ui-bootstrap/js/phplist.js"></script>

<script>
/* do not remove this from here */
$(document).ready(function(){
    if ( $('body').hasClass('invisible') ){
        myfunction();
    }
});
</script>